baseURL: ""
languageCode: "en-us"
title: "Sainath Dushatti"
paginate: 5
theme: "PaperModX"

module:
  imports:
  -path: github.com/reorx/hugo-PaperModX

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

# This section controls how Hugo handles minification of the site's output.
minify:
  disableXML: true # disables minification for XML files
  minifyOutput: true # enables minification for the rest of the site's output

# This section defines custom site parameters
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Sainath Dushatti # Title of the Website
  description: "Sainath Dushatti's Portfolio" # A short description of the site
  keywords: [Blog, Portfolio, Sainath Dushatti] # Keywords for the site for SEO purposes
  author: Me # author of the content
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light # controls the theme of the site.
  disableThemeToggle: false # enable the ability for users to toggle between light and dark themes

  ShowReadingTime: true # Displays the estimated reading time for each post
  ShowShareButtons: true # Enables social media share buttons on posts
  ShowPostNavLinks: true # Shows "Previous" and "Next" post navigation links
  ShowBreadCrumbs: true # Displays breadcrumb navigation to help users understand where they are on the site
  ShowCodeCopyButtons: true # enable copy buttons for code snippets, useful for technical blogs or documentation
  ShowWordCount: true # Displays the word count of posts
  ShowRssButtonInSectionTermList: true # shows an RSS feed button in section term lists for subscribing to updates
  UseHugoToc: true # Enables Hugo's Table of Contents (TOC) feature for long posts, which generates navigation for headings
  disableSpecial1stPost: false # enables special styling for the first post on the homepage
  disableScrollToTop: false # enables the "Scroll to Top" button that is typically present in blogs for easier navigation
  comments: false # Disables comments on posts
  hidemeta: false # Shows post metadata (like date, author, etc.)
  hideSummary: false # Post summary will be displayed on the homepage or other listing pages
  showtoc: false # Controls whether the Table of Contents is shown for individual posts
  tocopen: false # Table of Contents will not be expanded by default when it is shown

# This section manages static assets of the website
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "assets/staticImages/favicon.ico"
    favicon16x16: "assets/staticImages/favicon-16x16.png"
    favicon32x32: "assets/staticImages/favicon-32x32.png"
    apple_touch_icon: "assets/staticImages/apple-touch-icon.png"

  # configures profile display on the website
  profileMode:
    enabled: false # profile mode is disabled
    title: Sainath Dushatti # title of the profile
    subtitle: "Welcome to my corner of the internet" # text under the title
    imageUrl: ""
    imageWidth: 120
    imageHeight: 120
    imageTitle: Sainath Dushatti # alt text/tool tip
    buttons:
      - name: Posts
        url: /posts
      - name: Tags
        url: /tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my corner of the internet

  socialIcons:
    - name: x
      url: "https://x.com/iamsainathd"
    - name: github
      url: "https://github.com/sainathd07"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: example
      name: example.org
      url: https://example.org
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai